[ids]
1a2c
25a7
258a

[global]
oneshot_timeout=1000

[aliases]

backspace='
esc=`

y=up
u=y
i=u
o=i
p=o
[=p
]=backspace

h=down
j=h
k=j
l=k
;=l
'=;

b=left
n=right
m=b
,=n
.=m

[main]

space=overloadt2(control, space, 200)

capslock=overloadt2(meta, esc, 200)
enter=overloadt2(meta, enter, 200)

leftshift=overloadt2(shift, pageup, 200)
rightshift=overloadt2(shift, pagedown, 200)
leftalt=overloadt2(alt, home, 200)
rightalt=overloadt2(alt, end, 200)

leftcontrol=overloadt2(control,[, 200)
leftmeta=overloadt2(spacefn, ], 200)

rightcontrol=overloadt2(control, ., 200)
compose=overloadt2(spacefn, comma, 200)

[spacefn]
1=f1
2=f2
3=f3
4=f4
5=f5
6=f6
7=f7
8=f8
9=f9
0=f10
-=f11
==f12

